# Generated by Django 2.0.6 on 2018-06-09 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('1', 'Doador'), ('2', 'Adotador'), ('9', 'Administrador')], max_length=1)),
                ('nascimento', models.DateField()),
                ('data_registro', models.DateTimeField()),
                ('email_primario', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
