# Generated by Django 2.0.6 on 2018-06-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_registro',
        ),
    ]
