# Generated by Django 2.0.6 on 2018-06-09 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('1', 'Fêmea'), ('2', 'Macho'), ('3', 'Não identificado')], default='Não identificado', max_length=1)),
                ('peso', models.IntegerField()),
                ('vermifugado', models.BooleanField()),
                ('vacinado', models.BooleanField()),
                ('descricao', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Cao',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animais.Animal')),
                ('porte', models.CharField(choices=[('1', 'Pequeno'), ('2', 'Médio'), ('3', 'Grande'), ('4', 'Extra Grande')], default='Não identificado', max_length=1)),
            ],
            bases=('animais.animal',),
        ),
        migrations.AddField(
            model_name='animal',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to=settings.AUTH_USER_MODEL),
        ),
    ]
