# Generated by Django 2.0.6 on 2018-06-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animais.Animal')),
            ],
            bases=('animais.animal',),
        ),
        migrations.AddField(
            model_name='animal',
            name='pelagem',
            field=models.CharField(choices=[('1', 'Curta'), ('2', 'Longa')], default='Não identificada', max_length=1),
        ),
        migrations.AlterField(
            model_name='cao',
            name='porte',
            field=models.CharField(choices=[('1', 'Pequeno'), ('2', 'Médio'), ('3', 'Grande')], default='Não identificado', max_length=1),
        ),
    ]
