# Generated by Django 2.0.6 on 2018-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_auto_20180609_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.DateField(blank=True),
        ),
    ]
