# Generated by Django 2.0.6 on 2018-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_auto_20180609_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.DateField(),
        ),
    ]
