# Generated by Django 2.0.6 on 2018-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_auto_20180609_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
    ]
