# Generated by Django 2.0.6 on 2018-06-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0008_auto_20180609_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.IntegerField(blank=True),
        ),
    ]
