# Generated by Django 2.0.6 on 2018-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0010_auto_20180610_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
    ]
