# Generated by Django 2.0.6 on 2018-06-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0011_auto_20180610_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
