# Generated by Django 2.0.5 on 2018-06-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newsType',
            field=models.CharField(choices=[('News', 'News'), ('Ad', 'Ad'), ('AdoptionCenter', 'AdoptionCenter')], default='News', max_length=10),
        ),
    ]
