# Generated by Django 2.0.5 on 2018-06-19 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20180619_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='newsImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newsText',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newsTitle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='newsType',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='news',
            name='ntype',
            field=models.CharField(choices=[('AdoptionCenter', 'AdoptionCenter'), ('News', 'News'), ('Ad', 'Ad')], default='News', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
