# Generated by Django 2.0.5 on 2018-06-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20180619_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ntype',
            field=models.CharField(choices=[('Ad', 'Ad'), ('AdoptionCenter', 'AdoptionCenter'), ('News', 'News')], default='News', max_length=10),
        ),
    ]
