# Generated by Django 2.0.5 on 2018-06-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20180619_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ntype',
            field=models.CharField(choices=[('AdoptionCenter', 'AdoptionCenter'), ('Ad', 'Ad'), ('News', 'News')], default='News', max_length=10),
        ),
    ]
